beef:
    extension:
        dns_rebinding:
            enable: true
            name: 'DNS Rebinding'
            #Addresses are split into internal/external for more convenient attack
            #from LAN.
            address_http_internal: '192.168.0.104'
            address_http_external: '31.211.59.107'
            address_proxy_internal: '192.168.0.104'
            address_proxy_external: '31.211.59.107'
            port_http: 80
            port_proxy: 81
            debug_mode: true
