#
# Copyright (c) 2006-2012 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_chrome_extensions:
            enable: true
            category: "Chrome Extensions"
            name: "Get Chrome Extensions"
            description: "This module detects if any of the top 1,000 Chrome extensions are installed."
            authors: ["koto", "bcoles"]
            target:
                working: ["C"]
                not_working: ["All"]
