#  local_file_theft
#
#  Shamelessly plagurised from kos.io/xsspwn

beef:
    module:
        local_file_theft:
            enable: true
            category: "Misc"
            name: "Local File Theft"
            description: "Javascript may have filesystem access if we are running from a local resource and using the file:// scheme. This module checks common locations and cheekily snaches anything it finds. Shamelessly plagurised from http://kos.io/xsspwn. To test this module save the BeEF hook page locally and open in safari from the your localfile system."
            authors: ["mh"]
            target:
                working: ["All"]
