#   phonegap
#
beef:
    module:
        phonegap_file_upload:
            enable: true
            category: "Phonegap"
            name: "Upload File"
            description: "Upload files from device to a server of your choice."
            authors: ["mh"]
            target:
                working: ["All"]
