#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# https://www.exploit-db.com/exploits/40371/
#
beef:
    module:
        tenda_adsl_963281tan_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "Tenda ADSL Modem 963281TAN Router DNS Hijack"
            description: "Attempts to change the DNS setting on a Tenda ADSL2/2+ Modem 963281TAN router.<br/><br/>This router reportedly does not require authentication to change the DNS servers.<br/><br/>This module has not been tested."
            authors: ["Todor Donev"]
            target:
                unknown: ["ALL"]
