#   detect software
#
beef:
    module:
        Detect_software:
            enable: true
            category: "Host"
            name: "Detect Software"
            description: "Detects software installed on the host (Internet Explorer only)"
            authors: ["mh"]
            target:
                working: ["IE"]
                not_working: ["All"]
