#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        coinhive_miner:
            enable: true
            category: "Misc"
            name: "Coinhive Miner"
            description: "This module starts the Coinhive JavaScript Miner."
            authors: ["bcoles"]
            target:
                user_notify: ['ALL']
