#   phonegap
#
beef:
    module:
        List_files:
            enable: true
            category: "Phonegap"
            name: "List Files"
            description: "Examine device file system."
            authors: ["mh"]
            target:
                working: ["All"]
