#   phonegap
#
beef:
    module:
        Detect:
            enable: true
            category: "Phonegap"
            name: "Detect PhoneGap"
            description: "Detects if the PhoneGap API is present."
            authors: ["mh"]
            target:
                working: ["All"]
