#   phonegap
#
beef:
    module:
        Start_record_audio:
            enable: true
            category: "Phonegap"
            name: "Start Recording Audio"
            description: "Start recording audio."
            authors: ["mh"]
            target:
                working: ["All"]
