#   phonegap
#
beef:
    module:
        phonegap_beep:
            enable: true
            category: "Phonegap"
            name: "Beep"
            description: "Make the phone beep"
            authors: ["mh"]
            target:
                working: ["All"]
