#   phonegap persistence
#
beef:
    module:
        phonegap_persistence:
            enable: true
            category: "Phonegap"
            name: "Persistence"
            description: "Insert the BeEF hook into PhoneGap's index.html (iPhone only)"
            authors: ["mh"]
            target:
                working: ["All"]
