#   phonegap
#
beef:
    module:
        Stop_record_audio:
            enable: true
            category: "Phonegap"
            name: "Stop Recording Audio"
            description: "Stop recording audio."
            authors: ["mh"]
            target:
                working: ["All"]
